apiVersion: apps/v1
kind: Deployment
metadata:
  name: atef-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: atef-springboot
  template:
    metadata:
      labels:
        app: atef-springboot
    spec:
      containers:
        - name: springboot
          image: merikech/atef-docker-demo:atef-docker-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: atef-springboot
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: atef-springboot